export const mockData = {
    books: [
        {
            book_id: 1,
            title: "The Great Gatsby",
            author: "F. Scott Fitzgerald",
            genre: "Classic",
            publication_date: "1925-04-10",
            cover_image: "https://example.com/great-gatsby.jpg",
            summary: "A story about the mysterious millionaire Jay Gatsby and his passion for the beautiful Daisy Buchanan.",
            language: "English",
            library_id: 101,
            created_at: "2023-08-01T12:00:00Z",
            updated_at: "2023-08-01T12:00:00Z",
            is_locked: false,
            is_public: true,
            is_series: false,
        },
        {
            book_id: 2,
            title: "1984",
            author: "George Orwell",
            genre: "Dystopian",
            publication_date: "1949-06-08",
            cover_image: "https://example.com/1984.jpg",
            summary: "A chilling novel about a totalitarian regime that uses surveillance and mind control to maintain power.",
            language: "English",
            library_id: 102,
            created_at: "2023-08-02T12:00:00Z",
            updated_at: "2023-08-02T12:00:00Z",
            is_locked: false,
            is_public: true,
            is_series: false,
        },
        {
            book_id: 3,
            title: "To Kill a Mockingbird",
            author: "Harper Lee",
            genre: "Fiction",
            publication_date: "1960-07-11",
            cover_image: "https://example.com/to-kill-a-mockingbird.jpg",
            summary: "A novel set in the Great Depression, focusing on the racial injustice in the Deep South.",
            language: "English",
            library_id: 103,
            created_at: "2023-08-03T12:00:00Z",
            updated_at: "2023-08-03T12:00:00Z",
            is_locked: false,
            is_public: true,
            is_series: false,
        },
        {
            book_id: 4,
            title: "Pride and Prejudice",
            author: "Jane Austen",
            genre: "Romance",
            publication_date: "1813-01-28",
            cover_image: "https://example.com/pride-and-prejudice.jpg",
            summary: "A classic novel about the manners and matrimonial machinations among the British middle class.",
            language: "English",
            library_id: 104,
            created_at: "2023-08-04T12:00:00Z",
            updated_at: "2023-08-04T12:00:00Z",
            is_locked: false,
            is_public: true,
            is_series: false,
        },
        {
            book_id: 5,
            title: "The Catcher in the Rye",
            author: "J.D. Salinger",
            genre: "Fiction",
            publication_date: "1951-07-16",
            cover_image: "https://example.com/catcher-in-the-rye.jpg",
            summary: "A story about teenage angst and alienation, narrated by the iconic character Holden Caulfield.",
            language: "English",
            library_id: 105,
            created_at: "2023-08-05T12:00:00Z",
            updated_at: "2023-08-05T12:00:00Z",
            is_locked: false,
            is_public: true,
            is_series: false,
        },
        {
            book_id: 6,
            title: "The Hobbit",
            author: "J.R.R. Tolkien",
            genre: "Fantasy",
            publication_date: "1937-09-21",
            cover_image: "https://example.com/the-hobbit.jpg",
            summary: "A prelude to the Lord of the Rings trilogy, following the adventures of Bilbo Baggins.",
            language: "English",
            library_id: 106,
            created_at: "2023-08-06T12:00:00Z",
            updated_at: "2023-08-06T12:00:00Z",
            is_locked: false,
            is_public: true,
            is_series: true,
        },
        {
            book_id: 7,
            title: "Moby-Dick",
            author: "Herman Melville",
            genre: "Adventure",
            publication_date: "1851-10-18",
            cover_image: "https://example.com/moby-dick.jpg",
            summary: "The saga of Captain Ahab and his relentless pursuit of Moby Dick, the great white whale.",
            language: "English",
            library_id: 107,
            created_at: "2023-08-07T12:00:00Z",
            updated_at: "2023-08-07T12:00:00Z",
            is_locked: false,
            is_public: true,
            is_series: false,
        },
        {
            book_id: 8,
            title: "War and Peace",
            author: "Leo Tolstoy",
            genre: "Historical",
            publication_date: "1869-01-01",
            cover_image: "https://example.com/war-and-peace.jpg",
            summary: "A novel that intertwines the lives of private and public individuals during the time of the Napoleonic wars.",
            language: "Russian",
            library_id: 108,
            created_at: "2023-08-08T12:00:00Z",
            updated_at: "2023-08-08T12:00:00Z",
            is_locked: false,
            is_public: true,
            is_series: false,
        },
        {
            book_id: 9,
            title: "The Alchemist",
            author: "Paulo Coelho",
            genre: "Fiction",
            publication_date: "1988-04-15",
            cover_image: "https://example.com/the-alchemist.jpg",
            summary: "A philosophical story about a young shepherd on a journey to find his personal legend.",
            language: "Portuguese",
            library_id: 109,
            created_at: "2023-08-09T12:00:00Z",
            updated_at: "2023-08-09T12:00:00Z",
            is_locked: false,
            is_public: true,
            is_series: false,
        },
        {
            book_id: 10,
            title: "The Chronicles of Narnia",
            author: "C.S. Lewis",
            genre: "Fantasy",
            publication_date: "1950-10-16",
            cover_image: "https://example.com/chronicles-of-narnia.jpg",
            summary: "A series of seven fantasy novels that take place in the magical land of Narnia.",
            language: "English",
            library_id: 110,
            created_at: "2023-08-10T12:00:00Z",
            updated_at: "2023-08-10T12:00:00Z",
            is_locked: false,
            is_public: true,
            is_series: true,
        }
    ],
    chapters: [
        {
            chapter_id: 1,
            book_id: 1,
            chapter_number: 1,
            content: "In my younger and more vulnerable years my father gave me some advice that I’ve been turning over in my mind ever since.",
            is_oneshot: false,
            created_at: "2023-08-01T12:00:00Z",
            updated_at: "2023-08-01T12:00:00Z",
        },
        {
            chapter_id: 2,
            book_id: 1,
            chapter_number: 2,
            content: "About half way between West Egg and New York the motor-road hastily joins the railroad and runs beside it for a quarter of a mile.",
            is_oneshot: false,
            created_at: "2023-08-01T12:30:00Z",
            updated_at: "2023-08-01T12:30:00Z",
        },
        {
            chapter_id: 3,
            book_id: 2,
            chapter_number: 1,
            content: "It was a bright cold day in April, and the clocks were striking thirteen.",
            is_oneshot: false,
            created_at: "2023-08-02T12:00:00Z",
            updated_at: "2023-08-02T12:00:00Z",
        },
        {
            chapter_id: 4,
            book_id: 2,
            chapter_number: 2,
            content: "The Ministry of Truth contained, it was said, three thousand rooms above ground level, and corresponding ramifications below.",
            is_oneshot: false,
            created_at: "2023-08-02T12:30:00Z",
            updated_at: "2023-08-02T12:30:00Z",
        },
        {
            chapter_id: 5,
            book_id: 3,
            chapter_number: 1,
            content: "When he was nearly thirteen, my brother Jem got his arm badly broken at the elbow.",
            is_oneshot: false,
            created_at: "2023-08-03T12:00:00Z",
            updated_at: "2023-08-03T12:00:00Z",
        },
        {
            chapter_id: 6,
            book_id: 3,
            chapter_number: 2,
            content: "Dill left us early in September, to return to Meridian.",
            is_oneshot: false,
            created_at: "2023-08-03T12:30:00Z",
            updated_at: "2023-08-03T12:30:00Z",
        },
        {
            chapter_id: 7,
            book_id: 4,
            chapter_number: 1,
            content: "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.",
            is_oneshot: false,
            created_at: "2023-08-04T12:00:00Z",
            updated_at: "2023-08-04T12:00:00Z",
        },
        {
            chapter_id: 8,
            book_id: 5,
            chapter_number: 1,
            content: "If you really want to hear about it, the first thing you’ll probably want to know is where I was born, and what my lousy childhood was like.",
            is_oneshot: false,
            created_at: "2023-08-05T12:00:00Z",
            updated_at: "2023-08-05T12:00:00Z",
        },
        {
            chapter_id: 9,
            book_id: 6,
            chapter_number: 1,
            content: "In a hole in the ground there lived a hobbit.",
            is_oneshot: false,
            created_at: "2023-08-06T12:00:00Z",
            updated_at: "2023-08-06T12:00:00Z",
        },
        {
            chapter_id: 10,
            book_id: 10,
            chapter_number: 1,
            content: "Once there were four children whose names were Peter, Susan, Edmund, and Lucy.",
            is_oneshot: false,
            created_at: "2023-08-10T12:00:00Z",
            updated_at: "2023-08-10T12:00:00Z",
        }
    ]


}
